version: "2"

services: 
    hexoNginx:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        image: hexo-nginx
        user: root
        ports: 
            - 80:80
            - 443:443
        volumes:
            - /home/cert:/etc/nginx/cert
            - /home/images:/usr/share/nginx/images
